
CREATE VIEW [dbo].[v_StitchedPatients]
AS
SELECT [PATIENT_ID]
    ,  [PATIENT_NAME]
    ,  [FIRST_NAME]
    ,  [MIDDLE_NAME]
    ,  [LAST_NAME]
    ,  [MONITOR_NAME]
    ,  [ACCOUNT_ID]
    ,  [MRN_ID]
    , [UNIT_ID]
    , [UNIT_NAME]
    , [UNIT_CODE]
    , [FACILITY_ID]
    , [FACILITY_NAME]
    , [FACILITY_CODE]
    ,  [DOB]
    ,  dbo.fnUtcDateTimeToLocalTime(MIN([ADMIT_TIME_UTC])) AS [ADMIT_TIME]
    ,  dbo.fnUtcDateTimeToLocalTime(MAX([DISCHARGED_TIME_UTC])) AS [DISCHARGED_TIME]
    ,  [PATIENT_MONITOR_ID]
    ,  [STATUS]

FROM [dbo].[v_PatientSessions]
GROUP BY [PATIENT_ID]
       , [PATIENT_NAME]
       , [FIRST_NAME]
       , [MIDDLE_NAME]
       , [LAST_NAME]
       , [MONITOR_NAME]
       , [ACCOUNT_ID]
       , [MRN_ID]
       , [UNIT_ID]
       , [UNIT_NAME]
       , [UNIT_CODE]
       , [FACILITY_ID]
       , [FACILITY_NAME]
       , [FACILITY_CODE]
       , [DOB]
       , [PATIENT_MONITOR_ID]
       , [STATUS]
