CREATE proc [dbo].[usp_UpdateGatewaySettings]
(
@network_id NVARCHAR(30),
@enable_sw tinyint,
@recv_app NVARCHAR(30),
@send_app NVARCHAR(30),
@organization_id UNIQUEIDENTIFIER,
@send_sys_id UNIQUEIDENTIFIER,
@results_usid int,
@sleep_secs int,
@debug_level int,
@unit_org_id UNIQUEIDENTIFIER,
@patient_id_type char(4), 
@gateway_type char(4), 
@auto_assign_id_sw tinyint,
@new_mrn_format NVARCHAR(80),
@auto_chan_attach_sw tinyint,
@live_vitals_sw tinyint,
@live_waveform_size int,
@decnet_node int, 
@node_name char(5),
@nodes_excluded NVARCHAR(255),
@nodes_included NVARCHAR(255),
@timemaster_sw tinyint,
@waveform_size int,
@print_enabled_sw tinyint,
@auto_record_alarm_sw tinyint,
@collect_12_lead_sw tinyint,
@print_auto_record_sw tinyint,
@encryption_status bit,
@gateway_id UNIQUEIDENTIFIER
)
as
begin
update int_gateway 
                                                                set 
                                                                network_id =@network_id,
                                                                hostname = 'localhost',
                                                                enable_sw = @enable_sw,
                                                                reconnect_secs = 0,
                                                                recv_app = @recv_app,
                                                                send_app = @send_app,
                                                                organization_id =@organization_id ,
                                                                send_sys_id =@send_sys_id,
                                                                results_usid =@results_usid,
                                                                sleep_secs =@sleep_secs,
                                                                add_monitors_sw = 1,
                                                                debug_level =@debug_level,
                                                                unit_org_id =@unit_org_id, 
                                                                patient_id_type =@patient_id_type, 
                                                                add_patients_sw = 1,
                                                                gateway_type =@gateway_type,
                                                                auto_assign_id_sw = @auto_assign_id_sw,
                                                                new_mrn_format =@new_mrn_format,
                                                                auto_chan_attach_sw =@auto_chan_attach_sw,
                                                                live_vitals_sw =@live_vitals_sw,
                                                                live_waveform_size = @live_waveform_size,
                                                                decnet_node =@decnet_node, 
                                                                node_name = @node_name,
                                                                nodes_excluded = @nodes_excluded,
                                                                nodes_included =@nodes_included,
                                                                timemaster_sw = @timemaster_sw,
                                                                waveform_size = @waveform_size,
                                                                print_enabled_sw =@print_enabled_sw , 
                                                                auto_record_alarm_sw =@auto_record_alarm_sw,
                                                                collect_12_lead_sw = @collect_12_lead_sw,
                                                                print_auto_record_sw = @print_auto_record_sw,
                                                                encryption_status =@encryption_status
                                                                where gateway_id = @gateway_id
end
