//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplicationLocalized {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsX() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApplicationLocalized.StringsX", typeof(StringsX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to quit the application without configuring portal database?.
        /// </summary>
        internal static string CancelConfirmation {
            get {
                return ResourceManager.GetString("CancelConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database configuration successfully completed.
        /// </summary>
        internal static string ConfigSuccess {
            get {
                return ResourceManager.GetString("ConfigSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal database configuration failed.
        /// </summary>
        internal static string ConfigurationFailed {
            get {
                return ResourceManager.GetString("ConfigurationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacelabs DBInstaller.
        /// </summary>
        internal static string DBInstaller {
            get {
                return ResourceManager.GetString("DBInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Database restore path.
        /// </summary>
        internal static string InvalidDBRestorePath {
            get {
                return ResourceManager.GetString("InvalidDBRestorePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open connection with the specified server. Please provide a valid SA password..
        /// </summary>
        internal static string InvalidSAPassword {
            get {
                return ResourceManager.GetString("InvalidSAPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the specified path.
        /// </summary>
        internal static string NoAccess {
            get {
                return ResourceManager.GetString("NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL server is not installed on the local machine. Setup cannot proceed..
        /// </summary>
        internal static string NoSqlServerInstalled {
            get {
                return ResourceManager.GetString("NoSqlServerInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No upgrade required.Latest version of the Portal database already exists..
        /// </summary>
        internal static string NoUpgradeRequired {
            get {
                return ResourceManager.GetString("NoUpgradeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populating database with initial data....
        /// </summary>
        internal static string Progress_data {
            get {
                return ResourceManager.GetString("Progress_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing maintenance jobs....
        /// </summary>
        internal static string Progress_maintjobs {
            get {
                return ResourceManager.GetString("Progress_maintjobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing database schema....
        /// </summary>
        internal static string Progress_schema {
            get {
                return ResourceManager.GetString("Progress_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for configuration. Click &apos;Configure&apos; to proceed..
        /// </summary>
        internal static string ReadyforConfiguration {
            get {
                return ResourceManager.GetString("ReadyforConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for portal database upgrade.
        /// </summary>
        internal static string ReadyforUpgrade {
            get {
                return ResourceManager.GetString("ReadyforUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal database configuration is not supported on a Remote Sql server.
        /// </summary>
        internal static string RemoteSql {
            get {
                return ResourceManager.GetString("RemoteSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid path.
        /// </summary>
        internal static string SpecifyValidPath {
            get {
                return ResourceManager.GetString("SpecifyValidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is string 1..
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is string 2..
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is string 3..
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is string 4..
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is string 5..
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed SQL version is not supported by ICS.
        /// </summary>
        internal static string UnSupportedSqlVersion {
            get {
                return ResourceManager.GetString("UnSupportedSqlVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal database failed to upgrade to {0}.
        /// </summary>
        internal static string UpgradeFailed {
            get {
                return ResourceManager.GetString("UpgradeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal database is successfully upgraded to {0}.
        /// </summary>
        internal static string UpgradeSuccessful {
            get {
                return ResourceManager.GetString("UpgradeSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading portal database from {0} to {1}.
        /// </summary>
        internal static string UpgradeVersionInformation {
            get {
                return ResourceManager.GetString("UpgradeVersionInformation", resourceCulture);
            }
        }
    }
}
