CREATE PROCEDURE [dbo].[usp_AddNewGatewaySettings]
    (
     @gateway_id BIGINT,
     @gateway_type CHAR(4),
     @network_id NVARCHAR(30),
     @enable_sw TINYINT,
     @recv_app NVARCHAR(30),
     @send_app NVARCHAR(30),
     @organization_id BIGINT,
     @send_sys_id BIGINT,
     @results_usid INT,
     @sleep_secs INT,
     @debug_level INT,
     @unit_org_id BIGINT,
     @patient_id_type CHAR(4),
     @auto_assign_id_sw TINYINT,
     @new_mrn_format NVARCHAR(80),
     @auto_chan_attach_sw TINYINT,
     @live_vitals_sw TINYINT,
     @live_waveform_size INT,
     @decnet_node INT,
     @node_name CHAR(5),
     @nodes_excluded NVARCHAR(255),
     @nodes_included NVARCHAR(255),
     @timemaster_sw TINYINT,
     @waveform_size INT,
     @print_enabled_sw TINYINT,
     @auto_record_alarm_sw TINYINT,
     @collect_12_lead_sw TINYINT,
     @print_auto_record_sw TINYINT,
     @encryption_status BIT
    )
AS
BEGIN
    INSERT  INTO [dbo].[int_gateway]
            ([gateway_id],
             [gateway_type],
             [network_id],
             [hostname],
             [enable_sw],
             [recv_app],
             [send_app],
             [reconnect_secs],
             [organization_id],
             [send_sys_id],
             [results_usid],
             [sleep_secs],
             [add_monitors_sw],
             [add_patients_sw],
             [debug_level],
             [unit_org_id],
             [patient_id_type],
             [auto_assign_id_sw],
             [new_mrn_format],
             [auto_chan_attach_sw],
             [live_vitals_sw],
             [live_waveform_size],
             [decnet_node],
             [node_name],
             [nodes_excluded],
             [nodes_included],
             [timemaster_sw],
             [waveform_size],
             [print_enabled_sw],
             [auto_record_alarm_sw],
             [collect_12_lead_sw],
             [print_auto_record_sw],
             [encryption_status]
            )
    VALUES
            (@gateway_id,
             @gateway_type,
             @network_id,
             N'localhost',
             @enable_sw,
             @recv_app,
             @send_app,
             0,
             @organization_id,
             @send_sys_id,
             @results_usid,
             @sleep_secs,
             1,
             1,
             @debug_level,
             @unit_org_id,
             @patient_id_type,
             @auto_assign_id_sw,
             @new_mrn_format,
             @auto_chan_attach_sw,
             @live_vitals_sw,
             @live_waveform_size,
             @decnet_node,
             @node_name,
             @nodes_excluded,
             @nodes_included,
             @timemaster_sw,
             @waveform_size,
             @print_enabled_sw,
             @auto_record_alarm_sw,
             @collect_12_lead_sw,
             @print_auto_record_sw,
             @encryption_status
            );
END;

GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'usp_AddNewGatewaySettings';

