CREATE TABLE [dbo].[MR] (
    [MRID]   INT            IDENTITY (1, 1) NOT NULL,
    [Title]  NVARCHAR (255) NOT NULL,
    [Author] NVARCHAR (255) NOT NULL,
    CONSTRAINT [PK_MR] PRIMARY KEY CLUSTERED ([MRID] ASC) WITH (FILLFACTOR = 100)
);

