CREATE TABLE [dbo].[MRTC] (
    [MRID] INT NOT NULL,
    [TCID] INT NOT NULL,
    CONSTRAINT [PK_MRTC] PRIMARY KEY CLUSTERED ([MRID] ASC, [TCID] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK_MRTC_TC] FOREIGN KEY ([MRID]) REFERENCES [dbo].[MR] ([MRID])
);

