CREATE TABLE [dbo].[PR] (
    [PRID]   INT            IDENTITY (1, 1) NOT NULL,
    [Title]  NVARCHAR (255) NOT NULL,
    [Author] NVARCHAR (255) NOT NULL,
    CONSTRAINT [PK_PR] PRIMARY KEY CLUSTERED ([PRID] ASC) WITH (FILLFACTOR = 100)
);

