CREATE TABLE [dbo].[TC] (
    [TCID]   INT            IDENTITY (1, 1) NOT NULL,
    [Title]  NVARCHAR (255) NOT NULL,
    [Author] NVARCHAR (255) NOT NULL,
    CONSTRAINT [PK_TC] PRIMARY KEY CLUSTERED ([TCID] ASC) WITH (FILLFACTOR = 100)
);

