CREATE VIEW [dbo].[qryLaserDiskCollection]
AS
/*Generated by SQL Server Migration Assistant for Access version 5.3.0.*/
SELECT --TOP (9223372036854775807) WITH TIES
    [tm].[Title],
    [tc].[Category],
    [tm].[YearOfRelease]
FROM [dbo].[tblMovies] AS [tm]
    LEFT OUTER JOIN [dbo].[tblCategory] AS [tc]
        ON [tm].[CategoryID] = [tc].[CategoryID]
WHERE [tm].[Medium] = 'D';
--ORDER BY [tm].[Title];
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'[VideoCollection].[qryLaserDiskCollection]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'qryLaserDiskCollection';

