CREATE VIEW [dbo].[qryStars]
AS
/*Generated by SQL Server Migration Assistant for Access version 5.3.0.*/
SELECT
    [MovieActor].[MovieID],
    [MovieActor].[ActorID],
    [Actor].[FirstName],
    [Actor].[LastName]
FROM [Actor]
    INNER JOIN [MovieActor]
        ON [Actor].[ActorID] = [MovieActor].[ActorID];
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'[VideoCollection].[qryStars]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'qryStars';

