CREATE VIEW [dbo].[vwLaserDiskCollection]
AS
/*Generated by SQL Server Migration Assistant for Access version 5.3.0.*/
SELECT
    [m].[Title],
    [c].[Name] AS [Category],
    [m].[YearOfRelease]
FROM [dbo].[Movie] AS [m]
    LEFT OUTER JOIN [dbo].[Category] AS [c]
        ON [m].[CategoryID] = [c].[CategoryID];
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'[VideoCollection].[vwLaserDiskCollection]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'vwLaserDiskCollection';

