CREATE VIEW [dbo].[vwStar]
AS
/*Generated by SQL Server Migration Assistant for Access version 5.3.0.*/
SELECT
    [tms].[MovieID],
    [tms].[ActorID],
    [ta].[FirstName],
    [ta].[LastName]
FROM [dbo].[tblActors] AS [ta]
    INNER JOIN [dbo].[tblMovieStars] AS [tms]
        ON [ta].[ActorID] = [tms].[ActorID];
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'[VideoCollection].[vwStar]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'vwStar';

