//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalysisTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnalysisTime()
        {
            this.AnalysisEvents = new HashSet<AnalysisEvent>();
            this.int_beat_time_log = new HashSet<int_beat_time_log>();
            this.int_template_set_info = new HashSet<int_template_set_info>();
            this.PacerSpikeLogs = new HashSet<PacerSpikeLog>();
        }
    
        public System.Guid user_id { get; set; }
        public System.Guid patient_id { get; set; }
        public Nullable<long> start_ft { get; set; }
        public Nullable<long> end_ft { get; set; }
        public int analysis_type { get; set; }
        public System.DateTime insert_dt { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnalysisEvent> AnalysisEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<int_beat_time_log> int_beat_time_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<int_template_set_info> int_template_set_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PacerSpikeLog> PacerSpikeLogs { get; set; }
        public virtual TrendData TrendData { get; set; }
    }
}
