//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogData
    {
        public System.Guid AuditId { get; set; }
        public System.DateTime DateTime { get; set; }
        public string PatientID { get; set; }
        public string Application { get; set; }
        public string DeviceName { get; set; }
        public string Message { get; set; }
        public string ItemName { get; set; }
        public string OriginalValue { get; set; }
        public string NewValue { get; set; }
        public string ChangedBy { get; set; }
        public byte[] HashedValue { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
