//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfgValuesFactory
    {
        public string type_cd { get; set; }
        public string cfg_name { get; set; }
        public string cfg_value { get; set; }
        public string cfg_xml_value { get; set; }
        public string value_type { get; set; }
        public bool global_type { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
