//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsData
    {
        public long EventsDataID { get; set; }
        public int CategoryValue { get; set; }
        public int Type { get; set; }
        public int Subtype { get; set; }
        public float Value1 { get; set; }
        public float Value2 { get; set; }
        public int Status { get; set; }
        public int Valid_Leads { get; set; }
        public System.Guid TopicSessionId { get; set; }
        public System.Guid FeedTypeId { get; set; }
        public System.DateTime TimestampUTC { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
