//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class gts_waveform_index_rate
    {
        public long index_rate_id { get; set; }
        public int Wave_Rate_Index { get; set; }
        public int Current_Wavecount { get; set; }
        public int Active_Waveform { get; set; }
        public System.DateTime period_start { get; set; }
        public int period_len { get; set; }
        public System.DateTime creation_date { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
