//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class HL7_msg_list
    {
        public string list_name { get; set; }
        public int msg_no { get; set; }
        public int seq { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
