//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class HL7InboundMessage
    {
        public int MessageNo { get; set; }
        public string MessageStatus { get; set; }
        public string HL7Message { get; set; }
        public string HL7MessageResponse { get; set; }
        public string MessageSendingApplication { get; set; }
        public string MessageSendingFacility { get; set; }
        public string MessageType { get; set; }
        public string MessageTypeEventCode { get; set; }
        public string MessageControlId { get; set; }
        public string MessageVersion { get; set; }
        public System.DateTime MessageHeaderDate { get; set; }
        public System.DateTime MessageQueuedDate { get; set; }
        public Nullable<System.DateTime> MessageProcessedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual HL7PatientLink HL7PatientLink { get; set; }
    }
}
