//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_guarantor
    {
        public System.Guid patient_id { get; set; }
        public int seq_no { get; set; }
        public string type_cd { get; set; }
        public byte active_sw { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public Nullable<int> relationship_cid { get; set; }
        public Nullable<System.Guid> encounter_id { get; set; }
        public Nullable<System.Guid> ext_organization_id { get; set; }
        public Nullable<System.Guid> guarantor_person_id { get; set; }
        public Nullable<System.Guid> employer_id { get; set; }
        public Nullable<System.Guid> spouse_id { get; set; }
        public Nullable<System.Guid> contact_id { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
