//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_msg_log
    {
        public System.Guid msg_log_id { get; set; }
        public System.DateTime msg_dt { get; set; }
        public string product { get; set; }
        public Nullable<int> msg_template_id { get; set; }
        public string external_id { get; set; }
        public string msg_text { get; set; }
        public string type { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
