//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_test_group_detail
    {
        public int node_id { get; set; }
        public Nullable<int> test_cid { get; set; }
        public Nullable<int> univ_svc_cid { get; set; }
        public int rank { get; set; }
        public string display_type { get; set; }
        public string nm { get; set; }
        public Nullable<int> source_cid { get; set; }
        public Nullable<int> alias_test_cid { get; set; }
        public Nullable<int> alias_univ_svc_cid { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
