//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_loader_parameter
    {
        public string msg_event_code { get; set; }
        public Nullable<System.Guid> sys_id { get; set; }
        public Nullable<int> code_id { get; set; }
        public string parm { get; set; }
        public string value { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
