//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_site_link
    {
        public System.Guid link_id { get; set; }
        public string group_name { get; set; }
        public int group_rank { get; set; }
        public string display_name { get; set; }
        public int display_rank { get; set; }
        public string url { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
