//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_flowsheet_entry
    {
        public Nullable<System.Guid> flowsheet_entry_id { get; set; }
        public Nullable<int> test_cid { get; set; }
        public string data_type { get; set; }
        public Nullable<int> select_list_id { get; set; }
        public string units { get; set; }
        public Nullable<double> normal_float { get; set; }
        public Nullable<double> absolute_float_high { get; set; }
        public Nullable<double> absolute_float_low { get; set; }
        public Nullable<double> warning_float_high { get; set; }
        public Nullable<double> warning_float_low { get; set; }
        public Nullable<double> critical_float_high { get; set; }
        public Nullable<double> critical_float_low { get; set; }
        public Nullable<int> normal_int { get; set; }
        public Nullable<int> absolute_int_high { get; set; }
        public Nullable<int> absolute_int_low { get; set; }
        public Nullable<int> warning_int_high { get; set; }
        public Nullable<int> warning_int_low { get; set; }
        public Nullable<int> critical_int_high { get; set; }
        public Nullable<int> critical_int_low { get; set; }
        public string normal_string { get; set; }
        public Nullable<int> max_length { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
