//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_pref
    {
        public Nullable<System.Guid> user_id { get; set; }
        public Nullable<System.Guid> user_role_id { get; set; }
        public string application_id { get; set; }
        public byte[] xml_data { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
