//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_patient_monitor
    {
        public System.Guid patient_monitor_id { get; set; }
        public System.Guid patient_id { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public System.Guid monitor_id { get; set; }
        public Nullable<int> monitor_interval { get; set; }
        public string poll_type { get; set; }
        public Nullable<System.DateTime> monitor_connect_dt { get; set; }
        public Nullable<int> monitor_connect_num { get; set; }
        public Nullable<byte> disable_sw { get; set; }
        public Nullable<System.DateTime> last_poll_dt { get; set; }
        public Nullable<System.DateTime> last_result_dt { get; set; }
        public Nullable<System.DateTime> last_episodic_dt { get; set; }
        public Nullable<System.DateTime> poll_start_dt { get; set; }
        public Nullable<System.DateTime> poll_end_dt { get; set; }
        public Nullable<System.DateTime> last_outbound_dt { get; set; }
        public string monitor_status { get; set; }
        public string monitor_error { get; set; }
        public Nullable<System.Guid> encounter_id { get; set; }
        public Nullable<System.DateTime> live_until_dt { get; set; }
        public Nullable<byte> active_sw { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
