//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_diagnosis_drg
    {
        public System.Guid patient_id { get; set; }
        public System.Guid encounter_id { get; set; }
        public System.Guid account_id { get; set; }
        public int desc_key { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public Nullable<int> drg_cid { get; set; }
        public Nullable<System.DateTime> drg_assignment_dt { get; set; }
        public string drg_approval_ind { get; set; }
        public Nullable<int> drg_grper_rvw_cid { get; set; }
        public Nullable<int> drg_outlier_cid { get; set; }
        public Nullable<int> drg_outlier_days_no { get; set; }
        public Nullable<decimal> drg_outlier_cost_amt { get; set; }
        public Nullable<int> drg_grper_ver_type_cid { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
