//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_event_log
    {
        public System.Guid event_id { get; set; }
        public Nullable<System.Guid> patient_id { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> event_dt { get; set; }
        public int seq_num { get; set; }
        public string client { get; set; }
        public string description { get; set; }
        public Nullable<int> status { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
