//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_order_map
    {
        public System.Guid order_id { get; set; }
        public System.Guid patient_id { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public System.Guid organization_id { get; set; }
        public System.Guid sys_id { get; set; }
        public string order_xid { get; set; }
        public string type_cd { get; set; }
        public int seq_no { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
