//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_12lead_report_edit
    {
        public System.Guid report_id { get; set; }
        public System.DateTime insert_dt { get; set; }
        public Nullable<System.Guid> user_id { get; set; }
        public Nullable<short> version_number { get; set; }
        public string patient_name { get; set; }
        public string report_date { get; set; }
        public string report_time { get; set; }
        public string id_number { get; set; }
        public string birthdate { get; set; }
        public string age { get; set; }
        public string sex { get; set; }
        public string height { get; set; }
        public string weight { get; set; }
        public Nullable<int> vent_rate { get; set; }
        public Nullable<int> pr_interval { get; set; }
        public Nullable<int> qt { get; set; }
        public Nullable<int> qtc { get; set; }
        public Nullable<int> qrs_duration { get; set; }
        public Nullable<int> p_axis { get; set; }
        public Nullable<int> qrs_axis { get; set; }
        public Nullable<int> t_axis { get; set; }
        public string interpretation { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
