//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_12lead_report
    {
        public System.Guid report_id { get; set; }
        public System.Guid patient_id { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public System.Guid monitor_id { get; set; }
        public int report_number { get; set; }
        public System.DateTime report_dt { get; set; }
        public Nullable<byte> export_sw { get; set; }
        public byte[] report_data { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual int_12lead_report_new int_12lead_report_new { get; set; }
    }
}
