//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_SavedEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public int_SavedEvent()
        {
            this.int_savedevent_calipers = new HashSet<int_savedevent_calipers>();
            this.int_savedevent_event_log = new HashSet<int_savedevent_event_log>();
            this.int_savedevent_vitals = new HashSet<int_savedevent_vitals>();
            this.int_savedevent_waveform = new HashSet<int_savedevent_waveform>();
        }
    
        public System.Guid patient_id { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public System.Guid event_id { get; set; }
        public System.DateTime insert_dt { get; set; }
        public System.Guid user_id { get; set; }
        public int orig_event_category { get; set; }
        public int orig_event_type { get; set; }
        public System.DateTime start_dt { get; set; }
        public long start_ms { get; set; }
        public Nullable<long> center_ft { get; set; }
        public int duration { get; set; }
        public double value1 { get; set; }
        public Nullable<double> value2 { get; set; }
        public int print_format { get; set; }
        public string title { get; set; }
        public string comment { get; set; }
        public byte annotate_data { get; set; }
        public byte beat_color { get; set; }
        public int num_waveforms { get; set; }
        public int sweep_speed { get; set; }
        public int minutes_per_page { get; set; }
        public Nullable<int> thumbnailChannel { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual int_savedevent_beat_time_log int_savedevent_beat_time_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<int_savedevent_calipers> int_savedevent_calipers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<int_savedevent_event_log> int_savedevent_event_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<int_savedevent_vitals> int_savedevent_vitals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<int_savedevent_waveform> int_savedevent_waveform { get; set; }
    }
}
