//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_flowsheet_detail
    {
        public Nullable<System.Guid> flowsheet_detail_id { get; set; }
        public Nullable<System.Guid> flowsheet_id { get; set; }
        public string name { get; set; }
        public string detail_type { get; set; }
        public Nullable<System.Guid> parent_id { get; set; }
        public Nullable<int> seq { get; set; }
        public Nullable<int> test_cid { get; set; }
        public Nullable<byte> show_only_when_data { get; set; }
        public Nullable<byte> is_compressed { get; set; }
        public Nullable<byte> is_visible { get; set; }
        public Nullable<System.Guid> flowsheet_entry_id { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
