//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_insurance_policy
    {
        public System.Guid patient_id { get; set; }
        public short seq_no { get; set; }
        public Nullable<byte> active_sw { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public Nullable<System.Guid> account_id { get; set; }
        public string ins_policy_xid { get; set; }
        public Nullable<System.Guid> holder_id { get; set; }
        public Nullable<int> holder_rel_cid { get; set; }
        public Nullable<System.Guid> holder_emp_id { get; set; }
        public Nullable<System.Guid> plan_id { get; set; }
        public string group_xid { get; set; }
        public string group_nm { get; set; }
        public string company_plan_cid { get; set; }
        public Nullable<System.DateTime> plan_eff_dt { get; set; }
        public Nullable<System.DateTime> plan_exp_dt { get; set; }
        public Nullable<System.DateTime> verify_dt { get; set; }
        public Nullable<decimal> plcy_deductible_amt { get; set; }
        public Nullable<decimal> plcy_limit_amt { get; set; }
        public Nullable<short> plcy_limit_days_no { get; set; }
        public Nullable<decimal> rm_semi_private_rt { get; set; }
        public Nullable<decimal> rm_private_rt { get; set; }
        public string authorization_no { get; set; }
        public Nullable<System.DateTime> authorization_dt { get; set; }
        public string authorization_source { get; set; }
        public Nullable<System.Guid> authorization_cmt_id { get; set; }
        public Nullable<byte> cob_priority { get; set; }
        public string cob_code { get; set; }
        public string billing_status_code { get; set; }
        public Nullable<byte> rpt_of_eligibility_sw { get; set; }
        public Nullable<System.DateTime> rpt_of_eligibility_dt { get; set; }
        public string assignment_of_benefits_sw { get; set; }
        public Nullable<System.DateTime> notice_of_admit_dt { get; set; }
        public Nullable<System.Guid> verify_id { get; set; }
        public Nullable<short> lifetm_reserve_days_no { get; set; }
        public Nullable<short> delay_before_lr_day_no { get; set; }
        public Nullable<System.Guid> ins_contact_id { get; set; }
        public string plan_xid { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
