//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_hcp
    {
        public System.Guid hcp_id { get; set; }
        public Nullable<int> hcp_type_cid { get; set; }
        public string last_nm { get; set; }
        public string first_nm { get; set; }
        public string middle_nm { get; set; }
        public string degree { get; set; }
        public Nullable<byte> verification_sw { get; set; }
        public string doctor_ins_no_id { get; set; }
        public string doctor_dea_no { get; set; }
        public string medicare_id { get; set; }
        public string medicaid_id { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
