//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_misc_code
    {
        public int code_id { get; set; }
        public Nullable<System.Guid> organization_id { get; set; }
        public Nullable<System.Guid> sys_id { get; set; }
        public string category_cd { get; set; }
        public string method_cd { get; set; }
        public string code { get; set; }
        public Nullable<byte> verification_sw { get; set; }
        public string int_keystone_cd { get; set; }
        public string short_dsc { get; set; }
        public string spc_pcs_code { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
