//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_patient_list_detail
    {
        public System.Guid patient_list_id { get; set; }
        public System.Guid patient_id { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public System.Guid encounter_id { get; set; }
        public byte deleted { get; set; }
        public string new_results { get; set; }
        public Nullable<System.DateTime> viewed_results_dt { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
