//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_nxt_ascending_key
    {
        public string tbl_name { get; set; }
        public int ascend_key { get; set; }
        public string filler1 { get; set; }
        public string filler2 { get; set; }
        public string filler3 { get; set; }
        public string filler4 { get; set; }
        public string filler5 { get; set; }
        public string filler6 { get; set; }
        public string filler7 { get; set; }
        public string filler8 { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
