//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_savedevent_vitals
    {
        public System.Guid patient_id { get; set; }
        public System.Guid event_id { get; set; }
        public string gds_code { get; set; }
        public Nullable<System.DateTime> result_dt { get; set; }
        public string result_value { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual int_SavedEvent int_SavedEvent { get; set; }
    }
}
