//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_gateway_server
    {
        public System.Guid gateway_id { get; set; }
        public string server_name { get; set; }
        public int port { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
