//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_person
    {
        public System.Guid person_id { get; set; }
        public Nullable<System.Guid> new_patient_id { get; set; }
        public string first_nm { get; set; }
        public string middle_nm { get; set; }
        public string last_nm { get; set; }
        public string suffix { get; set; }
        public string tel_no { get; set; }
        public string line1_dsc { get; set; }
        public string line2_dsc { get; set; }
        public string line3_dsc { get; set; }
        public string city_nm { get; set; }
        public string state_code { get; set; }
        public string zip_code { get; set; }
        public Nullable<int> country_cid { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
