//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_print_job_et_waveform
    {
        public System.Guid Id { get; set; }
        public System.Guid DeviceSessionId { get; set; }
        public System.DateTime StartTimeUTC { get; set; }
        public System.DateTime EndTimeUTC { get; set; }
        public int SampleRate { get; set; }
        public byte[] WaveformData { get; set; }
        public int ChannelCode { get; set; }
        public string CdiLabel { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
