//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_outbound_queue
    {
        public System.Guid outbound_id { get; set; }
        public string msg_event { get; set; }
        public System.DateTime queued_dt { get; set; }
        public string msg_status { get; set; }
        public Nullable<System.DateTime> processed_dt { get; set; }
        public System.Guid patient_id { get; set; }
        public Nullable<System.Guid> order_id { get; set; }
        public Nullable<System.DateTime> obs_start_dt { get; set; }
        public Nullable<System.DateTime> obs_end_dt { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
