//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_bin_info
    {
        public System.Guid user_id { get; set; }
        public System.Guid patient_id { get; set; }
        public int template_set_index { get; set; }
        public int template_index { get; set; }
        public int bin_number { get; set; }
        public int source { get; set; }
        public int beat_count { get; set; }
        public int first_beat_number { get; set; }
        public int non_ignored_count { get; set; }
        public int first_non_ignored_beat { get; set; }
        public int iso_offset { get; set; }
        public int st_offset { get; set; }
        public int i_point { get; set; }
        public int j_point { get; set; }
        public int st_class { get; set; }
        public int singles_bin { get; set; }
        public int edit_bin { get; set; }
        public int subclass_number { get; set; }
        public byte[] bin_image { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual int_template_set_info int_template_set_info { get; set; }
    }
}
