//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_order_line
    {
        public System.Guid order_id { get; set; }
        public short seq_no { get; set; }
        public System.Guid patient_id { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public Nullable<int> status_cid { get; set; }
        public Nullable<int> prov_svc_cid { get; set; }
        public Nullable<int> univ_svc_cid { get; set; }
        public Nullable<int> transport_cid { get; set; }
        public string order_line_comment { get; set; }
        public string clin_info_comment { get; set; }
        public string reason_comment { get; set; }
        public Nullable<System.DateTime> scheduled_dt { get; set; }
        public Nullable<System.DateTime> observ_dt { get; set; }
        public Nullable<System.DateTime> status_chg_dt { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
