//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_channel_type
    {
        public System.Guid channel_type_id { get; set; }
        public int channel_code { get; set; }
        public Nullable<int> gds_cid { get; set; }
        public string label { get; set; }
        public Nullable<short> freq { get; set; }
        public Nullable<short> min_value { get; set; }
        public Nullable<short> max_value { get; set; }
        public Nullable<double> sweep_speed { get; set; }
        public Nullable<byte> priority { get; set; }
        public string type_cd { get; set; }
        public string color { get; set; }
        public string units { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
