//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_savedevent_waveform
    {
        public System.Guid patient_id { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public System.Guid event_id { get; set; }
        public int wave_index { get; set; }
        public int waveform_category { get; set; }
        public int lead { get; set; }
        public int resolution { get; set; }
        public int height { get; set; }
        public int waveform_type { get; set; }
        public byte visible { get; set; }
        public System.Guid channel_id { get; set; }
        public double scale { get; set; }
        public int scale_type { get; set; }
        public int scale_min { get; set; }
        public int scale_max { get; set; }
        public int scale_unit_type { get; set; }
        public int duration { get; set; }
        public int sample_rate { get; set; }
        public long sample_count { get; set; }
        public int num_Ypoints { get; set; }
        public int baseline { get; set; }
        public double Ypoints_per_unit { get; set; }
        public byte[] waveform_data { get; set; }
        public int num_timelogs { get; set; }
        public byte[] timelog_data { get; set; }
        public string waveform_color { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual int_SavedEvent int_SavedEvent { get; set; }
    }
}
