//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_patient_list_link
    {
        public System.Guid master_owner_id { get; set; }
        public System.Guid transfer_owner_id { get; set; }
        public Nullable<System.Guid> patient_id { get; set; }
        public System.DateTime start_dt { get; set; }
        public Nullable<System.DateTime> end_dt { get; set; }
        public string type_cd { get; set; }
        public Nullable<byte> deleted { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
