//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_broadcast_msg
    {
        public string timer_msg { get; set; }
        public string login_msg { get; set; }
        public Nullable<int> log_out_minutes { get; set; }
        public Nullable<int> keep_out { get; set; }
        public Nullable<int> disable_autoprocs { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
