//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_org_shift_sched
    {
        public System.Guid organization_id { get; set; }
        public string shift_nm { get; set; }
        public Nullable<System.DateTime> shift_start_tm { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
