//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_encounter_to_hcp_int
    {
        public System.Guid encounter_id { get; set; }
        public System.Guid hcp_id { get; set; }
        public string hcp_role_cd { get; set; }
        public Nullable<System.DateTime> end_dt { get; set; }
        public byte active_sw { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
