//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_savedevent_calipers
    {
        public System.Guid patient_id { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public System.Guid event_id { get; set; }
        public int channel_type { get; set; }
        public int caliper_type { get; set; }
        public string calipers_orientation { get; set; }
        public string caliper_text { get; set; }
        public long caliper_start_ms { get; set; }
        public long caliper_end_ms { get; set; }
        public int caliper_top { get; set; }
        public int caliper_bottom { get; set; }
        public Nullable<int> first_caliper_index { get; set; }
        public Nullable<int> second_caliper_index { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual int_SavedEvent int_SavedEvent { get; set; }
    }
}
