//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_procedure_hcp_int
    {
        public System.Guid encounter_id { get; set; }
        public int procedure_cid { get; set; }
        public int seq_no { get; set; }
        public int desc_key { get; set; }
        public System.Guid hcp_id { get; set; }
        public int proc_hcp_type_cid { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
