//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_system_parameter
    {
        public int system_parameter_id { get; set; }
        public string name { get; set; }
        public string parm_value { get; set; }
        public Nullable<byte> active_flag { get; set; }
        public Nullable<byte> after_discharge_sw { get; set; }
        public Nullable<byte> debug_sw { get; set; }
        public string descr { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
