//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_template_set_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public int_template_set_info()
        {
            this.int_bin_info = new HashSet<int_bin_info>();
        }
    
        public System.Guid user_id { get; set; }
        public System.Guid patient_id { get; set; }
        public int template_set_index { get; set; }
        public int lead_one { get; set; }
        public int lead_two { get; set; }
        public int number_of_bins { get; set; }
        public int number_of_templates { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual AnalysisTime AnalysisTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<int_bin_info> int_bin_info { get; set; }
    }
}
