//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class mpi_decision_log
    {
        public System.Guid candidate_id { get; set; }
        public System.Guid matched_id { get; set; }
        public int score { get; set; }
        public System.DateTime mod_dt { get; set; }
        public string status_code { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
