//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintRequest
    {
        public System.Guid Id { get; set; }
        public System.Guid PrintJobId { get; set; }
        public System.Guid RequestTypeEnumId { get; set; }
        public int RequestTypeEnumValue { get; set; }
        public System.DateTime TimestampUTC { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long PrintRequestID { get; set; }
    }
}
