//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceString
    {
        public string Name { get; set; }
        public string Value { get; set; }
        public string Comment { get; set; }
        public string Locale { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
