//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicSession
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TopicTypeId { get; set; }
        public Nullable<System.Guid> TopicInstanceId { get; set; }
        public Nullable<System.Guid> DeviceSessionId { get; set; }
        public Nullable<System.Guid> PatientSessionId { get; set; }
        public Nullable<System.DateTime> BeginTimeUTC { get; set; }
        public Nullable<System.DateTime> EndTimeUTC { get; set; }
        public long TopicSessionsID { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
