//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicFeedType
    {
        public System.Guid FeedTypeId { get; set; }
        public System.Guid TopicTypeId { get; set; }
        public int ChannelCode { get; set; }
        public System.Guid ChannelTypeId { get; set; }
        public Nullable<short> SampleRate { get; set; }
        public string Label { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
