//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_CombinedEncounters
    {
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string MRN_ID { get; set; }
        public string ACCOUNT_ID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.Guid> FACILITY_ID { get; set; }
        public Nullable<System.Guid> UNIT_ID { get; set; }
        public string ROOM { get; set; }
        public string BED { get; set; }
        public string MONITOR_NAME { get; set; }
        public Nullable<System.DateTime> LAST_RESULT { get; set; }
        public Nullable<System.DateTime> ADMIT { get; set; }
        public Nullable<System.DateTime> DISCHARGED { get; set; }
        public string SUBNET { get; set; }
        public System.Guid patient_id { get; set; }
        public string STATUS_CD { get; set; }
        public Nullable<int> MONITOR_CREATED { get; set; }
        public Nullable<System.Guid> FACILITY_PARENT_ID { get; set; }
        public Nullable<System.Guid> PATIENT_MONITOR_ID { get; set; }
        public string MERGE_CD { get; set; }
    }
}
