//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_LegacyMonitorCombined
    {
        public System.Guid monitor_id { get; set; }
        public Nullable<System.Guid> unit_org_id { get; set; }
        public string network_id { get; set; }
        public Nullable<int> node_id { get; set; }
        public Nullable<int> bed_id { get; set; }
        public Nullable<int> bed_cd { get; set; }
        public Nullable<int> room { get; set; }
        public Nullable<int> monitor_dsc { get; set; }
        public string monitor_name { get; set; }
        public string monitor_type_cd { get; set; }
        public string subnet { get; set; }
    }
}
