//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_LiveVitalsData
    {
        public string Name { get; set; }
        public string ResultValue { get; set; }
        public Nullable<System.Guid> TopicTypeId { get; set; }
        public System.Guid TopicSessionId { get; set; }
        public System.Guid PatientId { get; set; }
        public Nullable<System.Guid> TopicInstanceId { get; set; }
        public string GdsCode { get; set; }
        public System.DateTime DateTimeStampUTC { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public Nullable<long> FileDateTimeStamp { get; set; }
        public System.Guid FeedTypeId { get; set; }
    }
}
