//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_MetaData
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public System.Guid TypeId { get; set; }
        public Nullable<bool> IsLookUp { get; set; }
        public Nullable<System.Guid> TopicTypeId { get; set; }
        public string EntityName { get; set; }
        public string EntityMemberName { get; set; }
        public bool DisplayOnly { get; set; }
        public string PairName { get; set; }
        public string PairValue { get; set; }
        public Nullable<bool> PairLookup { get; set; }
        public string PairEntityName { get; set; }
        public string PairEntityMember { get; set; }
        public Nullable<System.Guid> PairMetaDataId { get; set; }
    }
}
