//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PrintJobs
    {
        public System.Guid print_job_id { get; set; }
        public string page_number { get; set; }
        public System.Guid patient_id { get; set; }
        public Nullable<int> orig_patient_id { get; set; }
        public Nullable<System.DateTime> job_net_dt { get; set; }
        public string descr { get; set; }
        public string data_node { get; set; }
        public string sweep_speed { get; set; }
        public string duration { get; set; }
        public string num_channels { get; set; }
        public string job_type { get; set; }
        public string bed { get; set; }
        public string recording_time { get; set; }
        public string annotation1 { get; set; }
        public string annotation2 { get; set; }
        public string annotation3 { get; set; }
        public string annotation4 { get; set; }
        public Nullable<int> print_bitmap { get; set; }
        public Nullable<int> twelve_lead_data { get; set; }
        public Nullable<int> end_of_job_sw { get; set; }
        public Nullable<int> print_sw { get; set; }
        public Nullable<int> printer_name { get; set; }
        public Nullable<int> last_printed_dt { get; set; }
        public Nullable<int> status_code { get; set; }
        public Nullable<int> status_msg { get; set; }
        public Nullable<int> start_rec { get; set; }
        public Nullable<int> row_dt { get; set; }
        public Nullable<int> row_id { get; set; }
    }
}
