//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaveformData
    {
        public System.Guid Id { get; set; }
        public int SampleCount { get; set; }
        public string TypeName { get; set; }
        public Nullable<System.Guid> TypeId { get; set; }
        public byte[] Samples { get; set; }
        public bool Compressed { get; set; }
        public System.Guid TopicSessionId { get; set; }
        public System.DateTime StartTimeUTC { get; set; }
        public System.DateTime EndTimeUTC { get; set; }
        public long WaveformDataID { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
