//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmResource
    {
        public Nullable<System.Guid> EnumGroupId { get; set; }
        public Nullable<int> IDEnumValue { get; set; }
        public string Label { get; set; }
        public string StrMessage { get; set; }
        public string StrLimitFormat { get; set; }
        public string StrValueFormat { get; set; }
        public string Locale { get; set; }
        public string Message { get; set; }
        public string LimitFormat { get; set; }
        public string ValueFormat { get; set; }
        public string AlarmTypeName { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
