//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdr_document_group
    {
        public Nullable<int> node_id { get; set; }
        public Nullable<int> rank { get; set; }
        public Nullable<int> parent_node_id { get; set; }
        public string node_name { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
