//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdr_restricted_organization
    {
        public System.Guid organization_id { get; set; }
        public System.Guid user_role_id { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
