//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdr_navigation_button
    {
        public string descr { get; set; }
        public Nullable<int> image_index { get; set; }
        public int position { get; set; }
        public string form_name { get; set; }
        public Nullable<int> node_id { get; set; }
        public string shortcut { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
