//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelInfoData
    {
        public System.Guid Id { get; set; }
        public System.Guid PrintRequestId { get; set; }
        public int ChannelIndex { get; set; }
        public bool IsPrimaryECG { get; set; }
        public bool IsSecondaryECG { get; set; }
        public bool IsNonWaveformType { get; set; }
        public Nullable<int> SampleRate { get; set; }
        public Nullable<int> Scale { get; set; }
        public Nullable<double> ScaleValue { get; set; }
        public Nullable<double> ScaleMin { get; set; }
        public Nullable<double> ScaleMax { get; set; }
        public Nullable<int> ScaleTypeEnumValue { get; set; }
        public Nullable<int> Baseline { get; set; }
        public Nullable<int> YPointsPerUnit { get; set; }
        public int ChannelType { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ChannelInfoDataID { get; set; }
    }
}
