//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class gts_input_rate
    {
        public long input_rate_id { get; set; }
        public string input_type { get; set; }
        public System.DateTime period_start { get; set; }
        public int period_len { get; set; }
        public int rate_counter { get; set; }
        public System.DateTime creation_date { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
