//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class HL7_out_queue
    {
        public string msg_status { get; set; }
        public string msg_no { get; set; }
        public string HL7_text_long { get; set; }
        public string HL7_text_short { get; set; }
        public string patient_id { get; set; }
        public string msh_system { get; set; }
        public string msh_organization { get; set; }
        public string msh_event_cd { get; set; }
        public string msh_msg_type { get; set; }
        public Nullable<System.DateTime> sent_dt { get; set; }
        public System.DateTime queued_dt { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
