//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_vital_live_temp
    {
        public System.Guid patient_id { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public System.Guid monitor_id { get; set; }
        public System.DateTime collect_dt { get; set; }
        public string vital_value { get; set; }
        public string vital_time { get; set; }
        public Nullable<System.DateTime> createdDT { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
