//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_patient_list
    {
        public System.Guid patient_list_id { get; set; }
        public Nullable<System.Guid> owner_id { get; set; }
        public string type_cd { get; set; }
        public string list_name { get; set; }
        public Nullable<int> svc_cid { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
