//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_patient_document
    {
        public Nullable<System.Guid> patient_id { get; set; }
        public Nullable<int> seq_no { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public string document_id { get; set; }
        public Nullable<int> node_id { get; set; }
        public Nullable<System.DateTime> document_dt { get; set; }
        public string document_desc { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
