//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_autoupdate_log
    {
        public string machine { get; set; }
        public System.DateTime action_dt { get; set; }
        public string prod { get; set; }
        public byte success { get; set; }
        public string reason { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
