//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_patient_link
    {
        public System.Guid orig_patient_id { get; set; }
        public System.Guid new_patient_id { get; set; }
        public Nullable<System.Guid> user_id { get; set; }
        public Nullable<System.Guid> monitor_id { get; set; }
        public System.DateTime mod_dt { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
