//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_print_job_et_alarm
    {
        public System.Guid AlarmId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public System.Guid TopicSessionId { get; set; }
        public System.Guid DeviceSessionId { get; set; }
        public System.DateTime AlarmStartTimeUTC { get; set; }
        public Nullable<System.DateTime> AlarmEndTimeUTC { get; set; }
        public string StrTitleLabel { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string ID1 { get; set; }
        public string ID2 { get; set; }
        public string DOB { get; set; }
        public string FacilityName { get; set; }
        public string UnitName { get; set; }
        public string MonitorName { get; set; }
        public string StrMessage { get; set; }
        public string StrLimitFormat { get; set; }
        public string StrValueFormat { get; set; }
        public string ViolatingValue { get; set; }
        public string SettingViolated { get; set; }
        public System.DateTime RowLastUpdatedOn { get; set; }
        public long IntPrintJobEtAlarmID { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
