//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_param_timetag
    {
        public System.Guid patient_id { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public System.Guid patient_channel_id { get; set; }
        public int timetag_type { get; set; }
        public long param_ft { get; set; }
        public System.DateTime param_dt { get; set; }
        public Nullable<int> value1 { get; set; }
        public Nullable<int> value2 { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
