//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_external_organization
    {
        public System.Guid ext_organization_id { get; set; }
        public string cat_code { get; set; }
        public string organization_nm { get; set; }
        public Nullable<System.Guid> parent_ext_organization_id { get; set; }
        public string organization_cd { get; set; }
        public string company_cons { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
