//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_specimen
    {
        public System.Guid specimen_id { get; set; }
        public System.Guid order_id { get; set; }
        public Nullable<System.Guid> patient_id { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public Nullable<int> univ_svc_cid { get; set; }
        public Nullable<int> status_cid { get; set; }
        public Nullable<System.Guid> encounter_id { get; set; }
        public Nullable<System.Guid> collect_id { get; set; }
        public string specimen_xid { get; set; }
        public Nullable<System.DateTime> procedure_dt { get; set; }
        public Nullable<int> source_cid { get; set; }
        public Nullable<int> body_site_cid { get; set; }
        public Nullable<System.Guid> comment_id { get; set; }
        public Nullable<System.DateTime> collect_dt { get; set; }
        public Nullable<short> collect_vol_qty { get; set; }
        public string collect_vol_unit_code_id { get; set; }
        public string collect_method { get; set; }
        public string source_additive { get; set; }
        public string action_code_id { get; set; }
        public Nullable<int> call_back_phone_cat_id { get; set; }
        public Nullable<int> fields_key { get; set; }
        public Nullable<System.DateTime> receive_dt { get; set; }
        public Nullable<int> handle_cid { get; set; }
        public Nullable<int> handle_cat_cid { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
