//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_translate
    {
        public string translate_cd { get; set; }
        public string form_id { get; set; }
        public string enu { get; set; }
        public string fra { get; set; }
        public string deu { get; set; }
        public string esp { get; set; }
        public string ita { get; set; }
        public string nld { get; set; }
        public string chs { get; set; }
        public System.DateTime insert_dt { get; set; }
        public string Pol { get; set; }
        public string ptb { get; set; }
        public string cze { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
