//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_db_ver
    {
        public string ver_code { get; set; }
        public System.DateTime install_dt { get; set; }
        public string status_cd { get; set; }
        public string pre_install_pgm { get; set; }
        public string pre_install_pgm_flags { get; set; }
        public string install_pgm { get; set; }
        public string install_pgm_flags { get; set; }
        public string post_install_pgm { get; set; }
        public string post_install_pgm_flags { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
