//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_channel_vital
    {
        public System.Guid channel_type_id { get; set; }
        public int gds_cid { get; set; }
        public string format_string { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
