//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_nok
    {
        public System.Guid patient_id { get; set; }
        public int seq_no { get; set; }
        public int notify_seq_no { get; set; }
        public byte active_flag { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public System.Guid nok_person_id { get; set; }
        public Nullable<System.Guid> contact_person_id { get; set; }
        public Nullable<int> relationship_cid { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
