//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_patient_image
    {
        public Nullable<System.Guid> patient_id { get; set; }
        public Nullable<System.Guid> order_id { get; set; }
        public short seq_no { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public Nullable<int> image_type_cid { get; set; }
        public string image_path { get; set; }
        public byte[] image { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
