//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_print_job_et_vitals
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public System.Guid TopicSessionId { get; set; }
        public string GDSCode { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public System.DateTime ResultTimeUTC { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
