//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_person_name
    {
        public System.Guid person_nm_id { get; set; }
        public string recognize_nm_cd { get; set; }
        public int seq_no { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public byte active_sw { get; set; }
        public string prefix { get; set; }
        public string first_nm { get; set; }
        public string middle_nm { get; set; }
        public string last_nm { get; set; }
        public string suffix { get; set; }
        public string degree { get; set; }
        public string mpi_lname_cons { get; set; }
        public string mpi_fname_cons { get; set; }
        public string mpi_mname_cons { get; set; }
        public Nullable<System.DateTime> start_dt { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
