//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_test_group
    {
        public int node_id { get; set; }
        public int rank { get; set; }
        public Nullable<byte> display_in_all { get; set; }
        public Nullable<int> parent_node_id { get; set; }
        public string display_type { get; set; }
        public string node_name { get; set; }
        public string parm_str { get; set; }
        public Nullable<byte> display_in_menu { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
