//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_patient_procedure
    {
        public System.Guid enc_id { get; set; }
        public int proc_cid { get; set; }
        public short seq_no { get; set; }
        public System.DateTime proc_dt { get; set; }
        public int proc_function_cid { get; set; }
        public short proc_minutes { get; set; }
        public Nullable<int> anesthesia_cid { get; set; }
        public Nullable<short> anesthesia_minutes { get; set; }
        public int consent_cid { get; set; }
        public Nullable<byte> proc_priority { get; set; }
        public int assoc_diag_cid { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
