//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_mon_request
    {
        public int req_id { get; set; }
        public System.Guid monitor_id { get; set; }
        public string req_type { get; set; }
        public string req_args { get; set; }
        public string status { get; set; }
        public System.DateTime mod_utc_dt { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
