//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_hcp_specialty
    {
        public System.Guid hcp_id { get; set; }
        public int specialty_cid { get; set; }
        public string govern_board { get; set; }
        public string certification_code { get; set; }
        public Nullable<System.DateTime> certification_dt { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
