//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_audit_log
    {
        public string login_id { get; set; }
        public string application_id { get; set; }
        public string patient_id { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public string audit_type { get; set; }
        public string device_name { get; set; }
        public string audit_descr { get; set; }
        public System.DateTime audit_dt { get; set; }
        public Nullable<System.Guid> encounter_id { get; set; }
        public Nullable<System.Guid> detail_id { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
