//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_specimen_group
    {
        public int rank { get; set; }
        public string source_cd { get; set; }
        public string specimen_group { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
