//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_hcp_license
    {
        public System.Guid hcp_id { get; set; }
        public int license_type_cid { get; set; }
        public string license_state_code { get; set; }
        public string license_xid { get; set; }
        public Nullable<System.DateTime> effective_dt { get; set; }
        public Nullable<System.DateTime> expiration_dt { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
