//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_procedure
    {
        public int encounter_id { get; set; }
        public int procedure_cid { get; set; }
        public bool seq_no { get; set; }
        public System.DateTime procedure_dt { get; set; }
        public int procedure_function_cid { get; set; }
        public bool procedure_minutes { get; set; }
        public Nullable<int> anesthesia_cid { get; set; }
        public Nullable<bool> anesthesia_minutes { get; set; }
        public int consent_cid { get; set; }
        public Nullable<bool> procedure_priority { get; set; }
        public int assoc_diag_cid { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
