//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_alarm_waveform
    {
        public System.Guid alarm_id { get; set; }
        public Nullable<byte> retrieved { get; set; }
        public string waveform_data { get; set; }
        public int seq_num { get; set; }
        public System.DateTime insert_dt { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
