//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_print_job
    {
        public System.Guid print_job_id { get; set; }
        public int page_number { get; set; }
        public Nullable<System.Guid> patient_id { get; set; }
        public Nullable<System.Guid> orig_patient_id { get; set; }
        public System.DateTime job_net_dt { get; set; }
        public string descr { get; set; }
        public int data_node { get; set; }
        public Nullable<double> sweep_speed { get; set; }
        public Nullable<double> duration { get; set; }
        public Nullable<int> num_channels { get; set; }
        public Nullable<System.Guid> alarm_id { get; set; }
        public string job_type { get; set; }
        public string title { get; set; }
        public string bed { get; set; }
        public string recording_time { get; set; }
        public Nullable<int> byte_height { get; set; }
        public Nullable<int> bitmap_height { get; set; }
        public Nullable<int> bitmap_width { get; set; }
        public Nullable<int> scale { get; set; }
        public string annotation1 { get; set; }
        public string annotation2 { get; set; }
        public string annotation3 { get; set; }
        public string annotation4 { get; set; }
        public byte[] print_bitmap { get; set; }
        public byte[] twelve_lead_data { get; set; }
        public Nullable<byte> end_of_job_sw { get; set; }
        public Nullable<byte> print_sw { get; set; }
        public string printer_name { get; set; }
        public Nullable<System.DateTime> last_printed_dt { get; set; }
        public string status_code { get; set; }
        public string status_msg { get; set; }
        public byte[] start_rec { get; set; }
        public System.DateTime row_dt { get; set; }
        public System.Guid row_id { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
