//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_user_contact
    {
        public System.Guid user_id { get; set; }
        public int seq { get; set; }
        public string contact_descr { get; set; }
        public string phone_num { get; set; }
        public string address_1 { get; set; }
        public string address_2 { get; set; }
        public string address_3 { get; set; }
        public string e_mail { get; set; }
        public string city { get; set; }
        public string state_province { get; set; }
        public string zip_postal { get; set; }
        public string country { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
