//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_sysgen_audit
    {
        public int int_sysgen_auditID { get; set; }
        public System.DateTime audit_dt { get; set; }
        public string audit { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
