//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadConfiguration
    {
        public string LeadName { get; set; }
        public string MonitorLoaderValue { get; set; }
        public string DataLoaderValue { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long LeadConfigurationID { get; set; }
    }
}
