//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LimitChangeData
    {
        public System.Guid Id { get; set; }
        public string High { get; set; }
        public string Low { get; set; }
        public string ExtremeHigh { get; set; }
        public string ExtremeLow { get; set; }
        public string Desat { get; set; }
        public System.DateTime AcquiredDateTimeUTC { get; set; }
        public System.Guid TopicSessionId { get; set; }
        public System.Guid FeedTypeId { get; set; }
        public System.Guid EnumGroupId { get; set; }
        public int IDEnumValue { get; set; }
        public long LimitChangeDataID { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
