//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class mpi_search_work
    {
        public Nullable<int> spid { get; set; }
        public Nullable<System.Guid> person_id { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
