//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class mpi_search_field
    {
        public string field_name { get; set; }
        public string col_name { get; set; }
        public short low { get; set; }
        public short high { get; set; }
        public string compare_type { get; set; }
        public string code_category { get; set; }
        public Nullable<int> is_secondary { get; set; }
        public Nullable<int> is_primary { get; set; }
        public string HL7_field { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
