//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientData
    {
        public System.Guid Id { get; set; }
        public System.Guid PatientSessionId { get; set; }
        public Nullable<System.Guid> DeviceSessionId { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string FirstName { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public string ID1 { get; set; }
        public string ID2 { get; set; }
        public string DOB { get; set; }
        public string Weight { get; set; }
        public string WeightUOM { get; set; }
        public string Height { get; set; }
        public string HeightUOM { get; set; }
        public string BSA { get; set; }
        public string Location { get; set; }
        public string PatientType { get; set; }
        public System.DateTime TimestampUTC { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
