//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableRowSpace
    {
        public long TableRowSpaceID { get; set; }
        public string DatabaseName { get; set; }
        public string SchemaName { get; set; }
        public string TableName { get; set; }
        public string IndexName { get; set; }
        public long RowCount { get; set; }
        public long TotalSpaceKB { get; set; }
        public long UsedSpaceKB { get; set; }
        public long UnusedSpaceKB { get; set; }
        public System.DateTime CreatedUTC { get; set; }
        public int IndexID { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
