//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ConfigurationData
    {
        public string ApplicationName { get; set; }
        public string SectionName { get; set; }
        public string SectionData { get; set; }
        public Nullable<System.DateTime> UpdatedTimeStampUTC { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
