//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DeviceSessionAssignment
    {
        public System.Guid DeviceSessionId { get; set; }
        public string FacilityName { get; set; }
        public string UnitName { get; set; }
        public string BedName { get; set; }
        public string MonitorName { get; set; }
        public string Channel { get; set; }
    }
}
