//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DiscardedOverlappingLegacyWaveformData
    {
        public System.Guid patient_id { get; set; }
        public System.Guid patient_channel_id { get; set; }
        public long start_ft { get; set; }
        public long end_ft { get; set; }
    }
}
