//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_LegacyChannelTypes
    {
        public System.Guid ChannelTypeId { get; set; }
        public System.Guid TopicTypeId { get; set; }
        public string TopicName { get; set; }
        public string CdiLabel { get; set; }
        public string TypeName { get; set; }
        public Nullable<System.Guid> TypeId { get; set; }
        public string SampleRate { get; set; }
        public string ChannelCode { get; set; }
        public string label { get; set; }
    }
}
