//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_LegacyMonitor
    {
        public System.Guid Id { get; set; }
        public string UnitOrgId { get; set; }
        public string NetworkId { get; set; }
        public Nullable<int> NodeId { get; set; }
        public Nullable<int> BedId { get; set; }
        public Nullable<int> BedCd { get; set; }
        public Nullable<int> Room { get; set; }
        public Nullable<int> Description { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Subnet { get; set; }
    }
}
