//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Patients
    {
        public System.Guid patient_id { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string patient_name { get; set; }
        public string ID1 { get; set; }
        public string ID2 { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string FACILITY_NAME { get; set; }
    }
}
