//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsPortalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_StitchedPatients
    {
        public System.Guid patient_id { get; set; }
        public string patient_name { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string MONITOR_NAME { get; set; }
        public string ACCOUNT_ID { get; set; }
        public string MRN_ID { get; set; }
        public Nullable<System.Guid> UNIT_ID { get; set; }
        public string UNIT_NAME { get; set; }
        public string UNIT_CODE { get; set; }
        public Nullable<System.Guid> FACILITY_ID { get; set; }
        public string FACILITY_NAME { get; set; }
        public string FACILITY_CODE { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> ADMIT_TIME { get; set; }
        public Nullable<System.DateTime> DISCHARGED_TIME { get; set; }
        public System.Guid PATIENT_MONITOR_ID { get; set; }
        public string STATUS { get; set; }
    }
}
